global:
  scrape_interval: 5s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ['gateway:8000']

  - job_name: users-service
    static_configs:
      - targets: ['users-service:3001']

  - job_name: notifications-service
    static_configs:
      - targets: ['notifications-service:3002']

  - job_name: products-service
    static_configs:
      - targets: ['products-service:3003']

  - job_name: orders-service
    static_configs:
      - targets: ['orders-service:3004']